# remap c-b to c-a
unbind C-b
set-option -g prefix C-a
set-option -g default-shell /usr/bin/zsh
# bind-key C-a send-prefix
# reload config file (change file location to your the tmux.conf you want to use)
# bind C-b source-file ~/.tmux.conf
# switch panes using Alt-arrow without prefix
# bind-key M-h previous-window
# bind-key M-l next-window
# don't rename windows automatically
# set-option -g allow-rename off
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 2

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-plugins " "
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-show-edge-icons false
set -g @dracula-transparent-powerline-bg false
set -g @dracula-battery-label false
set -g @dracula-show-battery-status true
set -g status-position top
# for left
# set -g @dracula-show-left-sep 

# for right symbol (can set any symbol you like as separator)
# set -g @dracula-show-right-sep 
# set -g @dracula-inverse-divider 

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
